apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-email-templates # Nombre para tu ConfigMap de plantillas
  namespace: nkp-pro-ex-02-fhrl9-rs5zn # Cambia esto si tu Alertmanager está en otro namespace
data:
  # El nombre de la clave aquí (e.g., custom_email.tmpl) será el nombre de tu archivo de plantilla.
  # Asegúrate de que este nombre sea único y no entre en conflicto con plantillas existentes.
  customi_email.tmpl: |
    {{ define "email.default.text" }} # Usamos un nombre de plantilla genérico para el cuerpo de texto
    ¡Alerta {{ .Status | toUpper }}!

    {{ range .Alerts }}
    -------------------------------------------------------
    Alerta: {{ .Labels.alertname }}
    Estado: {{ .Status | toUpper }}
    Severidad: {{ .Labels.severity | title }}
    {{ if .Labels.cluster }}Cluster: {{ .Labels.cluster }}{{ end }}
    {{ if .Labels.namespace }}Namespace: {{ .Labels.namespace }}{{ end }}
    {{ if .Annotations.summary }}Sumario: {{ .Annotations.summary }}{{ end }}
    {{ if .Annotations.description }}Descripción: {{ .Annotations.description }}{{ end }}
    {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}

    Detalles de Etiquetas:
    {{ range $key, $value := .Labels.SortedPairs }}
      {{ $key }}: {{ $value }}
    {{ end }}

    Detalles de Anotaciones:
    {{ range $key, $value := .Annotations.SortedPairs }}
      {{ $key }}: {{ $value }}
    {{ end }}

    Enlace a Alertmanager: {{ .GeneratorURL }}
    -------------------------------------------------------
    {{ end }}
    {{ end }}
