---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: WsZtcCNUtFFWsWv2pjebQAC7EM9V8rgj
  AWS_SECRET_ACCESS_KEY: NEo4uTAIH3aYAyJ4elRPFE5wn4azgUDC
kind: Secret
metadata:
  name: bucket-credentials
  namespace: apps
type: Opaque

